CREATE TABLE STUDENT
(
SID INT NOT NULL,
NAME VARCHAR(40),
DOB DATE,
PHYSICS INT,
CHEMISTRY INT,
MATHS INT
);
SELECT * FROM STUDENT;
INSERT INTO STUDENT (SID,NAME,DOB, PHYSICS,CHEMISTRY,MATHS) VALUES (001,'ALEENA','2000-03-03',50,40,50);
INSERT INTO STUDENT (SID,NAME,DOB, PHYSICS,CHEMISTRY,MATHS) VALUES (002,'ARUN','1999-08-13',40,30,70);
INSERT INTO STUDENT (SID,NAME,DOB, PHYSICS,CHEMISTRY,MATHS) VALUES (003,'BINU','2001-05-24',60,40,80);
INSERT INTO STUDENT (SID,NAME,DOB, PHYSICS,CHEMISTRY,MATHS) VALUES (004,'JASMIN','1997-01-01',70,80,70);
INSERT INTO STUDENT (SID,NAME,DOB, PHYSICS,CHEMISTRY,MATHS) VALUES (005,'VARSHA','1998-12-30',30,50,50);
SELECT SID,NAME FROM STUDENT  WHERE DOB= (SELECT MAX(DOB) FROM STUDENT) ;
SELECT * FROM STUDENT WHERE MATHS>=40 AND PHYSICS>=40 OR CHEMISTRY>=40;
ALTER TABLE STUDENT ADD COLUMN TOTAL INT;
ALTER TABLE STUDENT ADD COLUMN AVERAGE FLOAT;
SELECT NAME FROM STUDENT WHERE MATHS=(SELECT MAX(MATHS) FROM STUDENT);
SELECT NAME FROM STUDENT WHERE CHEMISTRY=(SELECT MIN(CHEMISTRY) FROM STUDENT);
UPDATE  STUDENT SET TOTAL=MATHS+PHYSICS+CHEMISTRY; 
UPDATE STUDENT SET AVERAGE=TOTAL/3;
SELECT * FROM STUDENT  ORDER BY  TOTAL DESC;
ALTER TABLE STUDENT RENAME COLUMN AVERAGE TO AVG_MARK;
SELECT * FROM STUDENT WHERE AVG_MARK>(SELECT AVG(AVG_MARK) FROM STUDENT);
SELECT AVG(AVG_MARK) FROM STUDENT;
SELECT COUNT(*) FROM STUDENT WHERE AVG_MARK>(SELECT AVG(AVG_MARK) FROM STUDENT);
