CREATE TABLE LOAN_ACCOUNTS
(
ACCNO CHAR(4),
CUST_NAME VARCHAR(15),
LOAN_AMOUNT DECIMAL(10,2),
INSTALLMENTS INT,
INT_RATE DECIMAL(10,2),
START_DATE DATE,
INTEREST DECIMAL(10,2)
);
DESCRIBE TABLE LOAN_ACCOUNTS; 
SELECT * FROM LOAN_ACCOUNTS;
ALTER TABLE LOAN_ACCOUNTS ADD COLUMN CATEGORY  VARCHAR(8);
INSERT INTO LOAN_ACCOUNTS(ACCNO,CUST_NAME,LOAN_AMOUNT,INSTALLMENTS,INT_RATE,START_DATE) VALUES (1001,'R.K GUPTA',300000.00,36,12.00,'2009-7-19');
INSERT INTO LOAN_ACCOUNTS(ACCNO,CUST_NAME,LOAN_AMOUNT,INSTALLMENTS,INT_RATE,START_DATE) VALUES (1002,'S.P SHARMA',500000.00,48,10.00,'2008-3-22');
INSERT INTO LOAN_ACCOUNTS(ACCNO,CUST_NAME,LOAN_AMOUNT,INSTALLMENTS,INT_RATE,START_DATE) VALUES (1003,'K.P JAIN',300000.00,36,NULL,'2007-8-3');
INSERT INTO LOAN_ACCOUNTS(ACCNO,CUST_NAME,LOAN_AMOUNT,INSTALLMENTS,INT_RATE,START_DATE) VALUES (1004,'M.P YADAV',800000.00,60,10.00,'2008-6-12');
INSERT INTO LOAN_ACCOUNTS(ACCNO,CUST_NAME,LOAN_AMOUNT,INSTALLMENTS,INT_RATE,START_DATE) VALUES (1005,'S.P SINHA',200000.00,36,12.50,'2010-3-1');
INSERT INTO LOAN_ACCOUNTS(ACCNO,CUST_NAME,LOAN_AMOUNT,INSTALLMENTS,INT_RATE,START_DATE) VALUES (1006,'P. SHARMA',700000.00,60,12.50,'2008-5-6');
INSERT INTO LOAN_ACCOUNTS(ACCNO,CUST_NAME,LOAN_AMOUNT,INSTALLMENTS,INT_RATE,START_DATE) VALUES (1007,'K.S DHALL',500000.00,48,NULL,'2008-5-3');
UPDATE LOAN_ACCOUNTS SET INT_RATE=11.50 WHERE INT_RATE IS NULL;
UPDATE LOAN_ACCOUNTS SET INT_RATE=INT_RATE+0.5 WHERE LOAN_AMOUNT>400000;
UPDATE LOAN_ACCOUNTS SET INTEREST=(LOAN_AMOUNT*INT_RATE*INSTALLMENTS)/(12*100);
DELETE FROM LOAN_ACCOUNTS WHERE START_DATE<'2008-1-1';
DELETE FROM LOAN_ACCOUNTS WHERE CUST_NAME LIKE 'K%';
SELECT * FROM LOAN_ACCOUNTS WHERE INSTALLMENTS<40;
SELECT ACCNO,LOAN_AMOUNT FROM LOAN_ACCOUNTS WHERE START_DATE>'2009-4-1';
SELECT INT_RATE FROM LOAN_ACCOUNTS WHERE START_DATE > '2009-4-1';
SELECT ACCNO, CUST_NAME, LOAN_AMOUNT FROM LOAN_ACCOUNTS WHERE CUST_NAME like '%SHARMA';
SELECT CUST_NAME,LOAN_AMOUNT FROM LOAN_ACCOUNTS WHERE CUST_NAME LIKE '%a';
SELECT ACCNO, CUST_NAME, LOAN_AMOUNT FROM LOAN_ACCOUNTS WHERE CUST_NAME LIKE '%a%';
SELECT ACCNO, CUST_NAME, LOAN_AMOUNT FROM LOAN_ACCOUNTS WHERE NOT(CUST_NAME LIKE '%P%');
DESCRIBE LOAN_ACCOUNTS;
SELECT * FROM LOAN_ACCOUNTS ORDER BY LOAN_AMOUNT ASC;
SELECT * FROM LOAN_ACCOUNTS ORDER BY START_DATE DESC;
SELECT * FROM LOAN_ACCOUNTS ORDER BY LOAN_AMOUNT, START_DATE DESC;
SELECT * FROM LOAN_ACCOUNTS WHERE CUST_NAME LIKE 'K%';
SELECT * FROM LOAN_ACCOUNTS WHERE INT_RATE IS NULL;
SELECT * FROM LOAN_ACCOUNTS WHERE INT_RATE is NOT NULL;
SELECT DISTINCT LOAN_AMOUNT FROM LOAN_ACCOUNTS ;
SELECT * FROM LOAN_ACCOUNTS WHERE START_DATE >'2008-12-31' AND INSTALLMENTS >36;
SELECT CUST_NAME,LOAN_AMOUNT FROM LOAN_ACCOUNTS WHERE LOAN_AMOUNT <500000 OR INT_RATE >12;
SELECT * FROM LOAN_ACCOUNTS WHERE YEAR(START_DATE)='2009';
SELECT * FROM LOAN_ACCOUNTS WHERE LOAN_AMOUNT BETWEEN 400000 AND 500000;
SELECT CUST_NAME,LOAN_AMOUNT FROM LOAN_ACCOUNTS WHERE INSTALLMENTS IN(26,36,48);
SELECT CUST_NAME,LOAN_AMOUNT,INT_RATE, CASE WHEN INT_RATE IS NULL THEN '0' ELSE INT_RATE END FROM LOAN_ACCOUNTS;
SELECT CUST_NAME,LOAN_AMOUNT,INT_RATE,CASE WHEN INT_RATE IS NULL THEN 'NO INTEREST' ELSE INT_RATE END FROM LOAN_ACCOUNTS;