CREATE  TABLE CUSTOMER1
(
CID INT PRIMARY KEY,
CNAME VARCHAR(20),
LOC VARCHAR(20),
SEX VARCHAR(1),
DOB DATE
);
CREATE TABLE BANK_BRN
(
BCODE VARCHAR(20) PRIMARY KEY NOT NULL,
BLOC VARCHAR(20),
BSATE VARCHAR(20)
);

CREATE TABLE DEPOSIT
(
DACNO NUMERIC(30) PRIMARY KEY NOT NULL,
DTYPE VARCHAR(20),
DDATE DATE,
DAMT NUMERIC(40)
);

CREATE TABLE LOANS
(
LACNO NUMERIC(30) PRIMARY KEY NOT NULL,
LTYPE VARCHAR(20),
LDATE DATE,
LAMT NUMERIC(30)
);

CREATE TABLE ACCOUNTS_IN
(
SLNO INT,
BCODE VARCHAR(20),
FOREIGN KEY(BCODE)
REFERENCES BANK_BRN(BCODE),
CID INT,
FOREIGN KEY(CID)
REFERENCES CUSTOMER1(CID)
);

CREATE TABLE DEPOSITOR
(
SLNO INT,
CID INT,
FOREIGN KEY(CID)
REFERENCES CUSTOMER1(CID),
DACNO NUMERIC(30),
FOREIGN KEY(DACNO)
REFERENCES DEPOSIT(DACNO) 
);

 CREATE TABLE BORROWER
 (
 SLNO INT,
 CID INT,
 FOREIGN KEY(CID)
 REFERENCES CUSTOMER1(CID),
 LACNO NUMERIC(30),
 FOREIGN KEY(LACNO)
 REFERENCES LOANS(LACNO)
 );
 SELECT * FROM CUSTOMER1;
 SELECT * FROM BANK_BRN;
 SELECT * FROM LOANS;
 SELECT * FROM ACCOUNTS_IN;
 DESCRIBE DEPOSITOR;
 